akonwi/git-plus

keymaps/git-plus.cson
atom-text-editor is a tag, not a class, so it should be used as `atom-text-editor`, not `.atom-text-editor`
=> Fix incorrect keymap syntax

lib/git-plus.coffee
The git-plus menu was only available when the current project was not a git repo as of 555a0d2ae91978ce3c6de962b33b7f406ccc158f. The menu is now always available.
=> Provide git-plus menu in all projects

lib/git.coffee
This error occurs when the git command is not found:
```
Failed to activate package named 'git-plus' Error: spawn EACCES
at exports._errnoException (util.js:753:11)
at ChildProcess.spawn (child_process.js:1160:11)
at Object.exports.spawn (child_process.js:993:9)
at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
at gitCmd (/Users/trangpham/.atom/packages/git-plus/lib/git.coffee:29:7)
at Object.gitRefreshIndex [as refresh] (/Users/trangpham/.atom/packages/git-plus/lib/git.coffee:79:3)
at Object.module.exports.activate (/Users/trangpham/.atom/packages/git-plus/lib/git-plus.coffee:71:11)
at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:235:27)
at …
```
=> Fail gracefully when git cmd not found

lib/git.coffee
The previous few sets of modifications didn't full fix #158. Even if the GitRepository object is null, it seems to try and refresh it when the window gets focus. This PR destroys the object in the `getRepo` method in both the if and else branches. I tested it out and this seems to fix #158` for good.
=> Fix destruction of GitRepository objects

lib/git.coffee
Since git-plus works on temporary repository objects, TreeView does not seem pick up on events from them. So in order to update TreeView, one *has* to update project's repositories, I think.
More involved fix would be to get project repositories  right away, if possible, and work on those, but I'm not sure if that would have any undesirable side effects.
=> Quick and dirty fix for #194

lib/git-plus.coffee, lib/models/git-commit.coffee
I have added a tiny fix that was preventing syntax highlighting occurring when using git-plus to make a commit on a branch that was ahead of its remote-tracking branch. This was caused by a lack of newline before the ‘Changes to be committed:’ line in the commit message.
Also inserted missing spaces in items to be displayed when viewing ‘Settings’ in Atom.
=> Added minor fix for syntax highlighting.

package.json
Currently you have to manually select another command to activate the package, I get the feeling that this is more of a bug than an intended feature.
=> Adding add-all-commit-and-push as an activation command.

lib/git.coffee
Pass process.env to BufferedProcess, otherwise package cant find git binary on PATH in Windows OSes.
=> Fix for akonwi/git-plus#322.

styles/git-plus.less
When update log is too large, and the pin icon is clicked to bring the log back up after it disappears automatically, there's no way to dismiss it without getting a new log that will overwrite the last one. 
Value could be set to anything, but I think this is a reasonable height to use because it's scrollable anyway, and shouldn't take *that* much way either way.
=> Fix height for long log outputs

lib/git.coffee, lib/models/git-commit.coffee, package.json, spec/git-spec.coffee, spec/models/git-commit-spec.coffee
In git.cmd, make the stderr callback identical to the stdout callback so that
they append to the same output string and make the exit callback reject(output)
if the exit code is non-zero, and resolve(output) if it is zero.
Fix git.getConfig to handle the rejection when a key is not set.
Add a catch() callback to GitCommit.commit that notifies the user of a commit
failure (so that failures won't be silent) and doesn't destroy the editor .
=> Fix bug #340 - commit editor/pane doesn't close.

README.md
Add space between markdown and header text so that header renders properly in Atom Settings view.
=> Fix Commit Window header

README.md, lib/git-plus-commands.coffee, lib/git-plus.coffee, lib/git.coffee, lib/models/git-open-changed-files.coffee, lib/views/status-list-view.coffee, package.json, spec/models/git-open-changed-files-spec.coffee
The command "Git Open Changed Files" (`git-plus:git-open-changed-files`) allows to quickly open all changed (added, moved or modified) files in the atom tabs. I think it can be quite useful when you return to work on some repo and want to observe all current (not commited) changes.
What do you think?
=> Add command to open all changed files

menus/git-plus.cson
Ampersands (`&`) don't show up in the actual menu (at least on macOS/X) so simply replace them with `+`.
=> Fix package menu items

lib/git-plus.coffee, lib/views/branch-list-view.coffee, menus/git-plus.cson
- Change `current` to `HEAD` branch list indicator
- Add `git-branch` to class list of branches modal
- Allow other packages to use branch _status-bar_ item
=> Improve branch list status-bar item and modal

lib/git-plus-commands.coffee, lib/git-plus.coffee, lib/models/git-merge.coffee, lib/views/merge-list-view.coffee, menus/git-plus.cson, package.json
TLDR: adds a new options that render:
$ git branchName --no-ff
_also menu > merge is now a submenu _
This feature for some development teams is intended to acomplish a better cvs management
Info:
- [Here](http://nvie.com/posts/a-successful-git-branching-model/)
- [and here](http://stackoverflow.com/questions/2850369/why-does-git-fast-forward-merges-by-default)
=> new Feature/merge without fast forward

lib/git-plus-commands.coffee, lib/git-plus.coffee, lib/git.coffee, menus/git-plus.cson, package.json
Didn't add any keybinding to avoid conflicts
=> add only modified files

CHANGELOG.md, lib/git-plus-commands.coffee, lib/git-plus.coffee, lib/grammars/diff.js, lib/models/git-merge.coffee, lib/models/git-show.coffee, lib/views/branch-list-view.coffee, lib/views/merge-list-view.coffee, menus/git-plus.cson, package.json, spec/models/git-merge-spec.coffee, spec/models/git-show-spec.coffee, spec/views/merge-list-view-spec.coffee
This adds an option in the settings to choose which format option for `git show` command. I've been using this because I needed the `fuller` option. Keeps `full` as the default. Not sure if it might be useful for others.
Regarding spec: want to tackle that, but I'll admit I'm a bit overwhelmed for how to write one for a command line option from the settings. Could you point me to a good example?
Potential future improvement: add the `format` and `tformat` options and a text field so users can enter their own. From [Git docs here](https://git-scm.com/docs/git-show) (search for "format:<string>")
=> Select format option in settings for git-show

lib/command-keystroke-humanizer.coffee, lib/views/git-palette-view.coffee, spec/command-keystroke-humanizer-spec.coffee
Hi, @akonwi 
This is an enhancement for [feature request](https://github.com/akonwi/git-plus/issues/559) which helps users to view commands' shortcuts next to their names in git plus menu.
Test file:
* spec/command-keystroke-humanizer-spec.coffee
Src file:
* lib/command-keystroke-humanizer.coffee
Please review and let me know what you think!
=> Display keyboard shortcut for the command in the Git Plus menu

lib/git.coffee
I think should allow people to right click git root path  to run some git command. Currently, git-plus does nothing,when right click git root path in tree-view.
Have you looked at the [guidelines](https://github.com/akonwi/git-plus/blob/master/.github/CONTRIBUTING.md) for contributing to this codebase?
Have you added tests and run `apm test`?
=> support right click git root path

lib/config.coffee, lib/views/tag-create-view.coffee, spec/views/tag-create-view-spec.coffee
Not a huge change, but my first modification to an Atom package, so I would encourage a careful review. Added a config boolean (and a test to cover it). Defaults to previous behavior. Really just changes `tag -a` to `tag -s` if the `signTags` boolean is `true`.
Without this, I don't get the pretty "Verified" text next to my tags in GitHub.
=> Allowing GPG signing of Git tags

lib/git-plus.coffee
this PR is a fix for #646 
disable `syntaxHighlighting` in settings and restart atom.
after atom is restarted, open the developer tools and run the following
code inside the console.
```javascript
var XXX_get = function() {
return atom.grammars.grammarForScopeName('source.diff')
};
var XXX_say = function() {
var g = XXX_get();
console.log('name:%s, package:%s, path:%s',
g.name, g.packageName, g.path);
};
XXX_say()
```
the expected output is as follows:
```
name:Diff, package:language-diff,
path:~/.atom/packages/language-diff/grammars/diff.cson
```
now open a new empty file and run `XXX_say()` in the console. the output
should be the same as in first run. next open the grammar selector and
type `diff` but do not yet change the grammar! there should be two
entries in the selector. `Diff` …
=> Keep the installed source.diff grammar

lib/config.coffee, lib/models/git-pull.coffee, spec/models/git-pull-spec.coffee
I added the configuration to always include the option '--autostash' with the pull comands just like the '--rebase' option.
3 tests added:
1. Only with the pullRebase option
2. Only with the pullAutostash option
3. With both pullRebase and pullAutostash options
=> Autostash option

lib/models/git-commit-amend.coffee, spec/models/git-commit-amend-spec.coffee
Solving the bug from issue #681 and #710
Sadly I didn't found any way to create a complete test for this function
I added a full test of the Commit Amend with a complex commit message, but I can see how some changes in the future might break the function without breaking the tests
Actually the original code have exactly the same problem, the tests cannot validate the return of the 'parse' function because it's private to the 'git-commit-amend' file
So if some future changes breaks the return to another valid return, but not the correct one (maybe missing one of the previous modifications), the tests will still pass
=> Amend complex commits

lib/grammars/diff.js
This fix is straightforward and simply implements the same solution used for digitallyserviced/semanticolor#27.
=> Fix #717 (registry.startIdForScope is not a function)

lib/config.coffee, lib/views/output-view.js
Added an option to always open bottom dock with the result of the command, regardless of bottom dock visibility.
=> Add option to always open bottom dock with result
