lib/models/git-branch.coffee, lib/views/status-view.coffee
This finishes the upgrade of `status-view.coffee` and `git-branch.coffee`. Also, a2f557c10f30839a49ea17510b9944812bcd52ce deleted the line that actually creates the new branch, so that is reintroduced.
I will keep adding commits to this branch to upgrade for the current atom API as I have time. If I have more after  any PRs are merged I'll just open another.
=> More api upgrades

stylesheets/git-plus.less
Fixes #159
This adds support for the shadow DOM styling per https://atom.io/docs/latest/upgrading/upgrading-your-ui-theme
=> Update styles to work with shadow DOM

keymaps/git-plus.cson, lib/git-plus-commands.coffee, lib/git-plus.coffee, lib/models/git-add-all-commit-and-push.coffee, lib/models/git-commit.coffee, menus/git-plus.cson
Adding a one-click command to submit everything you done to your remote repo
=> Add the command "Git Add All, Commit & Push"

lib/models/git-show.coffee, lib/views/log-list-view.coffee, lib/views/select-list-multiple-view.coffee
Commit messages should explain what happens here. If you want I can make them ready for 1.0.0 branch.
Rebased onto 1.0.0 branch. Have not yet checked if the rebase was a 100% success, will do that tomorrow.
//Edit: Merge conflicts plugin is a 100% fail for me on this point. I will fix this and force push onto this PR.
=> Fix terminal colors in commit displays & unique temporary files

lib/git-plus-commands.coffee, lib/models/git-branch.coffee, lib/views/branch-list-view.coffee, lib/views/remote-branch-list-view.coffee, package.json
I use remote checkouts pretty frequently in my workflow and thought this might be helpful for others - I did see that there was one issue logged for this as well.
=> Add remote checkout

lib/git-plus-commands.coffee, lib/git-plus.coffee, lib/models/git-pull.coffee, lib/views/pull-branch-list-view.coffee, lib/views/remote-list-view.coffee, menus/git-plus.cson, package.json
I usually prefer to use pull with rebase. But I don't use always with rebase, so I can't set it as default in my git configuration.
Thats why would be cool have this feature included on git-plus. And seems there is more people that want this feature #167.
Thanks
=> adds support for pull using rebase

menus/git-plus.cson
Because sometimes all you have to do is push!
This is a really small pull-request, I just added the push voice to the menu, for when you can't or wan't use the keybinding.
=> Added simple push to menu

lib/git-plus-commands.coffee
=> Port PR #305 to 5.5 branch

lib/models/git-show.coffee
=> disable color for git show

README.md
Hi there,
I migrated the command list to a table to make it easier to read.
Thanks.
=> Improved README.md by migrating commands to a table.

lib/views/pull-branch-list-view.coffee
the branch name extraction logic is in confirmed
=> fix issue #322

styles/git-plus.less
Fixes https://github.com/akonwi/git-plus/pull/334
=> Fix for output log height

lib/models/git-log.coffee, lib/views/log-list-view.coffee
[![https://gyazo.com/3e4cbaefe163169bf6dbc97045177827](https://i.gyazo.com/3e4cbaefe163169bf6dbc97045177827.gif)](https://gyazo.com/3e4cbaefe163169bf6dbc97045177827)
=> Support keyboard shortcuts

keymaps/git-plus.cson, lib/git-plus-commands.coffee, lib/git-plus.coffee, menus/git-plus.cson, package.json
For quick edits, pushes, consolidating the three steps into one is useful. I've done testing in my development environment and it works without issue.
Happy to put in unit tests if deemed necessary, just need to know where to put and what should be checked for. 
Thanks.
=> Add additional menu item: "Add and commit and push"

lib/git-plus.coffee, menus/git-plus.cson
- Fix tooltip
- Add option to disable status bar icon
=> Improve status-bar icon behaviour

lib/grammars/diff.js
I installed it and tried to show git logs at first. but I met issues it.
- https://github.com/akonwi/git-plus/issues/510
It occurred almost every time I click on any log.
I've fixed it and tested. it's okay now. 
I really would like you to check it ASAP.
thanks :)
=> - newTags data type is boolean.

git-plus, lib/grammars/diff.js
=> fix closing scopes in diffs

lib/git-plus.coffee
Have you added tests and run `apm test`?
=> fix merge without fast forward

lib/views/pull-branch-list-view.coffee, spec/views/pull-branch-list-view-spec.coffee
=> PullView: Only show branches from selected remote

README.md, lib/config.coffee, lib/git-plus-commands.coffee, lib/git-plus.coffee, lib/git.coffee, lib/models/git-fetch-all.coffee
=> Implement auto-fetch

lib/models/git-checkout-branch.js
Restores branch tracking when checking out remote branch
=> Fixes #633

menus/git-plus.cson
Have you looked at the [guidelines](https://github.com/akonwi/git-plus/blob/master/.github/CONTRIBUTING.md) for contributing to this codebase?
Have you added tests and run `apm test`?
=> Fixed minor typo

lib/models/git-diff.coffee
=> fix path when git root is not same as atom project

lib/models/git-commit-amend.coffee, lib/models/git-commit.coffee
- Fixes https://github.com/akonwi/git-plus/issues/738
- See issue description for more details
=> Destroy pane items, not panes

README.md
Have you looked at the [guidelines](https://github.com/akonwi/git-plus/blob/master/.github/CONTRIBUTING.md) for contributing to this codebase? yes
Have you added tests and run `apm test`? No additional tests, but the existing tests pass
=> Remove default keybindings from readme

lib/git-plus-commands.coffee, lib/git-plus.js
See https://github.com/akonwi/git-plus/issues/789
> Have you looked at the [guidelines](https://github.com/akonwi/git-plus/blob/master/.github/CONTRIBUTING.md) for contributing to this codebase?
Yes. :+1: 
> Have you added tests and run `apm test`?
I don't see anything relevant in the existing tests.
=> Add command to "Delete Branch (Local and Remote)";
